export enum MapBlocksBorderSprite{
    GroundDirtDown,
    GroundDirtUp,
    GroundDirtLeft,
    GroundDirtRight,
    GroundDirtDown2,
    GroundDirtUp2,
    GroundDirtLeft2,
    GroundDirtRight2,
    GroundDirtDownRight,
    GroundDirtUpLeft,
    GroundDirtDownLeft,
    GroundDirtUpRight,
    

    GroundGrassDown,
    GroundGrassUp,
    GroundGrassLeft,
    GroundGrassRight, 
    GroundGrassDown2,
    GroundGrassUp2,
    GroundGrassLeft2,
    GroundGrassRight2, 
    GroundGrassDownRight,
    GroundGrassUpLeft,
    GroundGrassDownLeft,
    GroundGrassUpRight,

    GroundSnowDown,
    GroundSnowUp,
    GroundSnowLeft,
    GroundSnowRight,
    GroundSnowDown2,
    GroundSnowUp2,
    GroundSnowLeft2,
    GroundSnowRight2,
    GroundSnowDownRight,
    GroundSnowUpLeft,
    GroundSnowDownLeft,
    GroundSnowUpRight,

    WaterDown,
    WaterUp,
    WaterLeft,
    WaterRight,
    WaterDownRight,
    WaterUpLeft,
    WaterDownLeft,
    WaterUpRight,

 }