export enum MapBlocksBorderSprite{
    GroundDirtDown,
    GroundDirtUp,
    GroundDirtLeft,
    GroundDirtRight,
    GroundGrassDown,
    GroundGrassUp,
    GroundGrassLeft,
    GroundGrassRight, 
    GroundSnowDown,
    GroundSnowUp,
    GroundSnowLeft,
    GroundSnowRight,
    WaterDown,
    WaterUp,
    WaterLeft,
    WaterRight,
 }